export default [
  {
    files: ["scripts/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        document: "readonly",
        window: "readonly",
        localStorage: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        setTimeout: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        URL: "readonly",
        console: "readonly",
        marked: "readonly",
        Mode: "readonly",
        Theme: "readonly",
        StateKey: "readonly",
        STATE_DEFAULTS: "readonly",
        getState: "readonly",
        setState: "readonly",
        THEMES: "readonly",
        THEME_CLASSES: "readonly",
        themeIcons: "readonly",
        DIY_FIELDS: "readonly",
        DIY_STATE_KEY: "readonly",
        validateStorage: "readonly",
        isValidHexColor: "readonly",
        applyDiyColors: "readonly",
        validateAndStoreHexColor: "readonly",
        validateAndStoreBool: "readonly",
        validateAndStoreFontSize: "readonly",
        handleShowLineNumbers: "readonly",
        handleMonospace: "readonly",
        handleWideMode: "readonly",
        handleTooltips: "readonly",
        handleWordCount: "readonly",
        handleThemeChange: "readonly",
        handleFontSizeChange: "readonly",
        handleModeChange: "readonly",
        renderViewMode: "readonly",
        renderEditMode: "readonly",
        toggleThemePicker: "readonly",
        updatePickerActiveState: "readonly",
        selectTheme: "readonly",
        syncDiyField: "readonly",
        handleDiyPickerInput: "readonly",
        handleDiyColorInput: "readonly",
        MODES: "readonly",
        updateLineNumbers: "readonly",
        updateWordCount: "readonly",
        flashModeToggle: "readonly",
        toggleMode: "readonly",
        clearText: "readonly",
        openFile: "readonly",
        handleFileSelect: "readonly",
        saveFile: "readonly",
        toggleSettings: "readonly",
        toggleBooleanState: "readonly",
        syncFullscreenIcon: "readonly",
      },
    },
    rules: {
      eqeqeq: ["error", "always"],
      "no-implicit-coercion": "error",
      "no-ternary": "error",
      "no-var": "error",
      "prefer-const": "error",
      "no-unused-vars": ["error", { vars: "local" }],
      "no-undef": "error",
      "no-negated-condition": "error",
      "no-nested-ternary": "error",
      "no-unneeded-ternary": "error",
    },
  },
];
