export default [
    {
        files: ['enums.js', 'state.js', 'themes.js', 'editor.js', 'ui.js', 'main.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'script',
            globals: {
                document: 'readonly',
                window: 'readonly',
                localStorage: 'readonly',
                confirm: 'readonly',
                prompt: 'readonly',
                setTimeout: 'readonly',
                FileReader: 'readonly',
                Blob: 'readonly',
                URL: 'readonly',
                console: 'readonly',
                marked: 'readonly',
                Mode: 'readonly',
                Theme: 'readonly',
                StateKey: 'readonly',
                STATE_DEFAULTS: 'readonly',
                getState: 'readonly',
                setState: 'readonly',
                THEMES: 'readonly',
                THEME_CLASSES: 'readonly',
                themeIcons: 'readonly',
                DIY_FIELDS: 'readonly',
                applyDiyColors: 'readonly',
                applyTheme: 'readonly',
                toggleThemePicker: 'readonly',
                updatePickerActiveState: 'readonly',
                selectTheme: 'readonly',
                parseColorToHex: 'readonly',
                syncDiyField: 'readonly',
                handleDiyPickerInput: 'readonly',
                handleDiyColorInput: 'readonly',
                MODES: 'readonly',
                updateLineNumbers: 'readonly',
                updateWordCount: 'readonly',
                updateModeIcon: 'readonly',
                flashModeToggle: 'readonly',
                toggleMode: 'readonly',
                updateRenderMode: 'readonly',
                clearText: 'readonly',
                openFile: 'readonly',
                handleFileSelect: 'readonly',
                saveFile: 'readonly',
                toggleSettings: 'readonly',
                updateFullscreenIcon: 'readonly'
            }
        },
        rules: {
            'eqeqeq': ['error', 'always'],
            'no-implicit-coercion': 'error',
            'no-ternary': 'error',
            'no-var': 'error',
            'prefer-const': 'error',
            'no-unused-vars': ['error', { vars: 'local' }],
            'no-undef': 'error',
            'no-negated-condition': 'error',
            'no-nested-ternary': 'error',
            'no-unneeded-ternary': 'error'
        }
    }
];
